name: Update verovio

on:
    schedule:
        - cron:  '0 0 * * *'
    workflow_dispatch: ~

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -
                name: Test
                run: |
                    echo "Hello world" > scripts/verovio-toolkit-wasm.js
            -
                name: Commit changes
                run: |
                    git config --global user.name "Wolfgang Drescher"
                    git config --global user.email "drescher.wolfgang+git@gmail.com"
                    git diff --quiet && git diff --staged --quiet || git commit -am "Update"
                    git push

